### ISSUE TITLE
大佬能把磁力下载封装成库就厉害了

### ISSUE THREAD

**Issue by ccflyy** [acgist/snail#1]
## 系统环境

> 系统信息（名称、版本）、软件信息（版本）

## 详细描述

> 问题建议详细描述

## 重现步骤

> 问题重现步骤

## 其他信息

> 系统日志、错误截图、配置截图

## 报告规范

* 标签：必须打上标签：问题、建议等
* 标题：[标签]简单描述（例：**[问题]磁力链接下载失败**）
* 重现步骤（选填）：提交[问题]类Issue时需要填写
* 其他信息（选填）：提交[问题]类Issue时需要填写
* 报告规范（删除）：提交时需要删除
* 更多参考[贡献规范](../CONTRIBUTING.md)

**Comment by acgist** [comment]
努力的方向
@ccflyy
