### ISSUE TITLE
jdk8版本

### ISSUE THREAD

**Issue by obhen233** [acgist/snail#13]
不打算提供个jdk8版本可以用的嘛

**Comment by acgist** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [acgist/snail] jdk8版本 (Issue #13)




 
不打算提供个jdk8版本可以用的嘛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
