### ISSUE TITLE
springboot整合snail 下载M3U8出现问题

### ISSUE THREAD

**Issue by acoffeeworld** [acgist/snail#15]
## 系统环境

* 系统信息（名称、版本）
* windows10
* 软件信息（版本）
springboot 2.6.7
idea2021.1.3

## 详细描述
如图
![image](https://user-images.githubusercontent.com/17959717/168843435-17f1fe36-0937-431d-9b18-6e49621fe288.png)
提交下载任务后 下载M3U8只能得到m3u8文件
![image](https://user-images.githubusercontent.com/17959717/168843507-2434731e-0c12-452f-a66c-588222b664e9.png)
## 期望
提交m3u8下载任务后 自动转换m3u8文件 合成mp4或其他视频文件...
问题建议详细描述

## 重现步骤

* spring bean配置
```java
@Configuration
public class SnailConfig {
    @Bean
    public Snail snail() {
        log.warn("SnailConfig.snail()");
        return Snail.SnailBuilder.newBuilder()
                .enableAllProtocol()
                .buildSync();
    }
}
```
* server实现
```java
public Object doGetM3U8(String url) {
        ITaskSession download = null;
        try {
            download = snail.download(url);
            snail.lockDownload();

            while (true) {
                ITaskSessionStatus.Status status = download.getStatus();
                if (Objects.equals(ITaskSessionStatus.Status.COMPLETED, status) | Objects.equals(ITaskSessionStatus.Status.FAIL, status)) {
                    break;
                }
                System.out.println("等待下载完成...");
            }
            snail.unlockDownload();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            snail.unlockDownload();
        }
        return null;
    }
```

问题重现步骤

## 其他信息

* 系统日志
* 错误截图
* 

* 配置截图
* 
![image](https://user-images.githubusercontent.com/17959717/168843705-84a7e814-fbe3-41d0-8056-27ce73056351.png)

* **注意检查隐私信息**

## 报告规范

* 标签：必须打上标签：问题、建议
* 标题：[标签]简单描述（例：[问题]磁力链接下载失败）
* 重现步骤（选填）：提交[问题]类Issue时需要填写
* 其他信息（选填）：提交[问题]类Issue时需要填写
* 报告规范（删除）：提交时需要删除
* 更多参考[贡献规范](../CONTRIBUTING.md)

**Comment by acgist** [comment]
你看下文件里面有没有内容或者日志有没有异常，有可能M3U8文件没有下载成功。

```
snail.lockDownload();
```

这个会等待下载完成，所以不用后面的`while`循环了

@acoffeeworld
