### ISSUE TITLE
Android可以使用此库吗？ed2k://格式是否考虑支持？

### ISSUE THREAD

**Issue by fismas** [acgist/snail#20]
Android可以使用此库吗？
ed2k://格式是否考虑支持？

**Comment by acgist** [comment]
安卓不能直接使用
电驴不会支持，这个官方文档也不好找，而且现在国内很少有人用了。

**Comment by fismas** [comment]
好的，谢谢。有计划支持Android吗？
另外提供个线索，早些迅雷开源库是支持ed2k等多种格式，不知是否会帮助到你。下边提供个地址：https://github.com/YuntaoWei/BtPlayer/tree/master/thunder

**Comment by fismas** [comment]
ed2k格式在视频类的用的还是挺多的。如 https://www.yjys.top/guoju/25058.htm

**Comment by acgist** [comment]
其实安卓和ed2k我之前都做过，安卓主要是JDK很多API不一样放弃了，电驴协议资源服务器很多都连不上，所以两个都放弃了。
这个项目以后基本上指挥修复BUG了，不会做新功能开发了。
