### ISSUE TITLE
Very good library. There are some questions.

### ISSUE THREAD

**Issue by master255** [acgist/snail#4]
I studied the library.
1. Do you have any plans to implement sequential data downloads? Streaming mode?
2. Do you have any plans to adapt to Android? For mobile devices? For Android 4.4+?

**Comment by acgist** [comment]
1. The pieces are selected sequentially, but it is not mandatory, and I expect faster downloads
2. Mobile will not be considered for the time being

**Comment by master255** [comment]
Ok. Very bad. Success in programming.

**Comment by master255** [comment]
@acgist If you change your mind and want to do a torrent streaming for Android, write me. I'll help in any way I can.

**Comment by acgist** [comment]
Ok, Thanks.

@master255

**Comment by master255** [comment]
@acgist I’ve heard that VPNs are blocked in China.
I have a brilliant app that can be used throughout China: [DHT City](https://t.me/dht_money/3) ([download link](https://drive.google.com/drive/folders/1Ikt0nv75zOC7InBChTXqvMiluKEGbDCt)) is a messenger with a built-in VPN, video and audio calls, and file transfer.
The connection works via Libp2p from Protocol Labs and uses the most modern protocols, which are impossible to block. If necessary, you can add any protocols. It has a modular system for adding protocols. And all protocols are used simultaneously – via multiplexing.
All of this is based on 3 DHT. There is no server. Therefore, the messenger can be used by an unlimited number of people.

Register as a user. To create your own permanently running nodes, register as a manager.
