### ISSUE TITLE
[交流]建议交流

### ISSUE THREAD

**Issue by acgist** [acgist/snail#5]
建议交流

**Comment by AnserBaby** [comment]
我以为安卓能用呢

**Comment by acgist** [comment]
> 我以为安卓能用呢

安卓不支持Java11，所以就没写了。

**Comment by mrdear** [comment]
下载模块能单独发布到中央仓库不？想基于该项目做一个群晖内置的下载套件，展示端使用WEB方式搞定。

**Comment by acgist** [comment]
> 下载模块能单独发布到中央仓库不？想基于该项目做一个群晖内置的下载套件，展示端使用WEB方式搞定。

已经放到Maven中央仓库了，可以通过socket连接端口`16888`发送系统消息管理任务。

```xml
<dependency>
    <groupId>com.acgist</groupId>
    <artifactId>snail</artifactId>
    <version>1.5.0</version>
</dependency>
```

@mrdear

**Comment by nikolamakin** [comment]
BT 功能啥时候上啊，我想帮楼主

**Comment by acgist** [comment]
> BT 功能啥时候上啊，我想帮楼主

BT已经可以使用了

@nikolamakin

**Comment by nikolamakin** [comment]
能边下载边播放吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acgist/snail"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 晚上6:40
收件人:&nbsp;"acgist/snail"<snail@noreply.github.com&gt;;
抄送:&nbsp;"金哲"<nikolamakin@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [acgist/snail] [交流]建议交流 (#5)





  
BT 功能啥时候上啊，我想帮楼主
  
BT已经可以使用了
 
@nikolamakin

**Comment by acgist** [comment]
没有实现播放功能
可以指定下载位置，播放可以直接使用系统播放器试试

@nikolamakin
