### ISSUE TITLE
磁力链接  mac  下安装失败

### ISSUE THREAD

**Issue by RalapChen** [acgist/snail#7]
## 系统环境

> 系统信息：mac  pro

## 详细描述

> mac下载稳定版后，解压是jar包，点击打开。报错“未能启动java JAR 文件 snail.javafx-1.6.0.jar”

## 重现步骤

> 点击就会重现

## 其他信息

> 系统日志、错误截图、配置截图

## 报告规范

* 标签：必须打上标签：问题、建议等
* 标题：[标签]简单描述（例：**[问题]磁力链接下载失败**）
* 重现步骤（选填）：提交[问题]类Issue时需要填写
* 其他信息（选填）：提交[问题]类Issue时需要填写
* 报告规范（删除）：提交时需要删除
* 更多参考[贡献规范](../CONTRIBUTING.md)

**Comment by acgist** [comment]
有安装jdk11吗



---原始邮件---
发件人: "RalapChen"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 下午5:51
收件人: "acgist/snail"<snail@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [acgist/snail] 磁力链接  mac  下安装失败 (#7)




 
系统环境
  
系统信息：mac  pro
  
详细描述
  
mac下载稳定版后，解压是jar包，点击打开。报错“未能启动java JAR 文件 snail.javafx-1.6.0.jar”
  
重现步骤
  
点击就会重现
  
其他信息
  
系统日志、错误截图、配置截图
  
报告规范
  
标签：必须打上标签：问题、建议等 

标题：[标签]简单描述（例：[问题]磁力链接下载失败） 

重现步骤（选填）：提交[问题]类Issue时需要填写 

其他信息（选填）：提交[问题]类Issue时需要填写 

报告规范（删除）：提交时需要删除 

更多参考贡献规范

**Comment by acgist** [comment]
有安装JDK11吗 @RalapChen
